name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build specific projects on Linux with dotnet
      run: dotnet build ./src/CarsRental.Crosscutting/CarsRental.Crosscutting.csproj --configuration Release && dotnet build ./src/CarsRental.Domain/CarsRental.Domain.csproj --configuration Release && dotnet build ./src/CarsRental.Infrastructure/CarsRental.Infrastructure.csproj  --configuration Release && dotnet build ./src/CarsRental.Infrastructure.Tests/CarsRental.Infrastructure.Tests.csproj --configuration Release
    - name: Infrastructure Tests
      run: dotnet test .\src\CarsRental.Infrastructure.Tests\CarsRental.Infrastructure.Tests.csproj